---
name: "Template Test one"
on:
  workflow_call:
    inputs:
      release-branch:
        required: true
        type: string
      manual-approval-env:
        required: true
        type: string
            
concurrency:
  group: ${{ github.workflow }}-one-${{ inputs.release-branch }}
  cancel-in-progress: false

jobs:
  print-settings:
    name: 'Print-settings'
    runs-on: ubuntu-latest
    steps:
      - name: Print inputs
        run: |
          echo "release branch is ${{ inputs.release-branch }} "
          echo "manual-approval-env is ${{ inputs.manual-approval-env }}"

  manual-approval:
    name: 'Manual Approval'
    needs: [print-settings]
    environment:
      name: ${{ inputs.manual-approval-env }}
    runs-on: ubuntu-latest
    steps:
    - name: manual approve
      run: |
          echo "Manually approved Plan Triggered"

  test-job:
    name: 'Terraform Destroy'
    needs: [print-settings, manual-approval]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.release-branch }}    
...
