---
name: "Trigger Test"
on:
  workflow_dispatch:

jobs:
  workflow-dispatch-test-one:
    name: 'Workflow dispatch-test-one'
    uses: ./.github/workflows/template-number-one.yaml
    with:
      release-branch: ${{ github.ref_name }}
      manual-approval-env: "test"
    secrets: inherit

  workflow-dispatch-test-two:
    name: 'Workflow dispatch-test-one'
    uses: ./.github/workflows/template-number-two.yaml
    with:
      release-branch: ${{ github.ref_name }}
      manual-approval-env: "test"
    secrets: inherit
...
